#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

export SESSION="${SESSION:-cellular-levels-023-100}"
export WORKERS="${WORKERS:-15}"
export LEVEL_START="${LEVEL_START:-23}"
export LEVEL_END="${LEVEL_END:-100}"
export STABLE_TICKS="${STABLE_TICKS:-200}"
export SOURCE_RATE="${SOURCE_RATE:-12}"
export SOURCE_RATE_STEPS="${SOURCE_RATE_STEPS:-12,16,20,24}"
export WIN_DURATION_TICKS="${WIN_DURATION_TICKS:-$STABLE_TICKS}"
export WIN_RECENT_FLOW_WINDOW_TICKS="${WIN_RECENT_FLOW_WINDOW_TICKS:-200}"
export REQUIRED_ALIVE_TICKS_AT_END="${REQUIRED_ALIVE_TICKS_AT_END:-0}"
export SOLUTION_TICKS="${SOLUTION_TICKS:-900}"
export NEED_ATTEMPTS="${NEED_ATTEMPTS:-64}"
export LAYOUT_CANDIDATES="${LAYOUT_CANDIDATES:-11}"
export EVENT_CAPACITY="${EVENT_CAPACITY:-1048576}"
export HEARTBEAT_SECONDS="${HEARTBEAT_SECONDS:-60}"
export PROGRESS_STRIDE="${PROGRESS_STRIDE:-128}"

JOB="${1:-stable-levels-023-100-200}"
exec bash scripts/start_puzzle_level_batch_tmux.sh "$JOB"
